
'use strict';

module.exports =
  { Types:
    { FETCH_PIZZA_DATA_LOADING: 'FETCH_PIZZA_DATA_LOADING'
    , FETCH_PIZZA_DATA_SUCCESS: 'FETCH_PIZZA_DATA_SUCCESS'
    , FETCH_PIZZA_DATA_FAILURE: 'FETCH_PIZZA_DATA_FAILURE'
    , SELECT_NEW_PIZZA_SIZE:    'SELECT_NEW_PIZZA_SIZE'
    , SELECT_NEW_TOPPING:       'SELECT_NEW_TOPPING'
    , MODIFY_CART_ITEMS:         'MODIFY_CART_ITEMS'
    }
  };
