
'use strict';

module.exports =
  { Types:
    { FETCH_PIZZA_DATA_LOADING: 'FETCH_PIZZA_DATA_LOADING'
    , FETCH_PIZZA_DATA_SUCCESS: 'FETCH_PIZZA_DATA_SUCCESS'
    , FETCH_PIZZA_DATA_FAILURE: 'FETCH_PIZZA_DATA_FAILURE'
    , SELECT_NEW_PIZZA_SIZE:    'SELECT_NEW_PIZZA_SIZE'
    }
  };
