---
  env:
    browser: true
    node: false
    commonjs: true
  globals:
    Promise: true
  plugins:
    - eslint-plugin-react
  parserOptions:
    ecmaVersion: 6
    ecmaFeatures:
      jsx: true
      arrowFunctions: true
      objectLiteralShorthandMethods: true
      objectLiteralShorthandProperties: true
      restParams: true
      templateStrings: true
  rules:
    eqeqeq: 2
    no-undef: 2
    curly: 2
    comma-dangle: 2
    semi: 2
    no-empty: 2
    no-dupe-keys: 2
    no-dupe-args: 2
    no-debugger: 2
    no-console: 0
    no-shadow: 2
    quotes: [2, single]
    no-multi-spaces: 0
    new-cap: 0
    key-spacing: 0
    dot-notation: 1
    no-underscore-dangle: 0
    no-unused-vars: 1
    max-len: [ 2, 80, 4, {ignoreComments: true, ignoreUrls: true} ]
    react/display-name: 1
    react/forbid-prop-types: 0
    react/jsx-boolean-value: 1
    react/jsx-closing-bracket-location: 1
    react/jsx-curly-spacing: 1
    react/jsx-handler-names: 1
    react/jsx-indent-props: [2, 2]
    react/jsx-key: 1
    react/jsx-max-props-per-line: 1
    react/jsx-no-bind: 1
    react/jsx-no-duplicate-props: 1
    react/jsx-no-literals: 1
    react/jsx-no-undef: 1
    react/jsx-pascal-case: 1
    react/jsx-sort-props: 1
    react/jsx-uses-react: 1
    react/jsx-uses-vars: 1
    react/no-danger: 1
    react/no-deprecated: 1
    react/no-did-mount-set-state: 1
    react/no-did-update-set-state: 1
    react/no-direct-mutation-state: 1
    react/no-is-mounted: 1
    react/no-multi-comp: 1
    react/no-set-state: 1
    react/no-string-refs: 1
    react/no-unknown-property: 1
    react/prefer-es6-class: 0
    react/prop-types: 1
    react/react-in-jsx-scope: 1
    react/self-closing-comp: 1
    react/sort-comp: 1
    react/sort-prop-types: 1
    react/jsx-wrap-multilines: 1
